### ISSUE TITLE
[BUG] I have deployed to vecel 

### ISSUE THREAD

**Issue by Pandimadhubabu** [Web-SyncPlay/Web-SyncPlay#16]
https://sync-play.vercel.app/. But not working

**Comment by Yasamato** [comment]
Hey, have you made sure to pass along an publicly accessible URI to your redis instance?

**Comment by Pandimadhubabu** [comment]
Can please tell me how to do it or check it

**Comment by Yasamato** [comment]
You need to either host a [redis](https://redis.io) storage yourself on your own hardware and make them accessible to your vercel deployment or use a hosted version like for example [upstash](https://upstash.com), where you get a limited free tier.

After you've started your redis instance, you have to pass the URI to your vercel deployment as an environmental variable like `REDIS_URL=redis://username:password@your-ip:6379` and make sure it is accessible from the vercel deployment itself.
