### ISSUE TITLE
[BUG] Seek behaviour on twitch glitchy

### ISSUE THREAD

**Issue by gatesyp** [Web-SyncPlay/Web-SyncPlay#4]
Nice work with this! Pretty awesome. 

My main usecase is using this to watch Twitch videos. The seeking behaviour a bit glitchy: 
https://www.loom.com/share/712571305cf14992a6b113f6aee1cc08

Steps to reproduce: 
Create a room in the app
Using twitch url: https://www.twitch.tv/videos/1038423984
Start clicking around on the playback bar

I wonder if this is caused by the react-player implementation ?

**Comment by Yasamato** [comment]
Sadly this is not a react-player issue... :/
From what I found after investigating this is more of a twitch player api related problem.

A seek with the seek bar triggers sends to the  server the seek command and is refered back.
Local player seeks to that time, twitch will seek to that time, but will report a false current time for a single tick, resulting in the strange jumping you see.

So the seek bar is initially at the correct position, gets a wrong current time from the twitch api and jumps to the reported position and then it finially gets the actual correct current time jumping back to where it already was correctly positioned...

I am not sure if I want to manually add a workaround that specific vendor. Maybe if I have some time for it and am up for it, but don't expect that anytime soon (if ever) or they fix it themself.

Workaround from a user perspective is: ignore the jumping seekbar and continue seeking after the jumping settled

**Comment by gatesyp** [comment]
👍 makes sense. thanks for looking into it + the writeup

I may add a workaround + PR it to react-player, will keep you updated
